TM=.
LIB=..
MYLIB=$(LIB)/tmj_portmux

install:
	cp tmjportmux_gen.sh $(LIB)/tmjportmux_gen
	-mkdir $(MYLIB)
	cp tmjportmux_skel_part1a $(MYLIB)
	cp tmjportmux_skel_part1b $(MYLIB)
	cp tmjportmux_skel_part1c $(MYLIB)
	cp tmjportmux_skel_part1d $(MYLIB)
	cp tmjportmux_skel_part2 $(MYLIB)
	cp virtual1.v $(MYLIB)
	cp simple_dual_port_ram_single_clock.v $(MYLIB)
